ARG BASE
FROM ${BASE} AS builder
RUN wget --progress=dot:mega -O - https://github.com/gentoo-mirror/gentoo/archive/master.tar.gz | tar -xz \
 && mv gentoo-master /var/db/repos/gentoo \
 && echo '*/* bindist' >> /etc/portage/package.use/bindist \
 && FEATURES="-sandbox -usersandbox" emerge --jobs 8 -1vDtuN @world \
 && emerge --depclean \
 && rm -r /var/db/repos/gentoo

FROM scratch
COPY --from=builder / /
